name: Python lint and format check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint

    - name: Check if all python files properly formatted with black
      run: |
        black --config black_config.toml --check ./src/combined

    - name: Lint with pylint
      run: |
        pylint --rcfile=.pylintrc ./src/combined/scripts/*.py
